export const ROUTE_SEGMENTS = {
  SPLASH: "",
  LOGIN: "login",
  PIN_LOGIN: "pin-login",
  FORGOT_PASSWORD: "forgot-password",
  JOIN_BY_CODE: "join-by-code",
  SELECT_KITCHEN: "select-kitchen",
  DASHBOARD: "dashboard",
  ORGANIZATION: "organization",
  USERS: "users",
  KITCHEN_MANAGEMENT: "kitchen-management",
  LIST_MONITORING: "list-monitoring",
  RECIPE_BOOK: "recipes",
  ACTIVITY_LOGS: "activity-logs",
  ADMIN: "admin",
  RESTAURANT_USAGE: "restaurant-usage",
  SUBSCRIPTION: "subscription",
};

export const ROUTES = {
  ROOT: "/",
  SPLASH: "/",
  LOGIN: "/login",
  PIN_LOGIN: "/pin-login",
  FORGOT_PASSWORD: "/forgot-password",
  JOIN_BY_CODE: "/join-by-code",
  SELECT_KITCHEN: "/select-kitchen",
  DASHBOARD: "/dashboard",
  ORGANIZATION: "/organization",
  USERS: "/users",
  KITCHEN_MANAGEMENT: "/kitchen-management",
  LIST_MONITORING: "/list-monitoring",
  RECIPE_BOOK: "/recipes",
  ACTIVITY_LOGS: "/activity-logs",
  ADMIN: "/admin",
  ADMIN_ROLES: "/admin/roles",
  ADMIN_RESTAURANT_USAGE: "/admin/restaurant-usage",
  SUBSCRIPTION: "/subscription",
};
