export const COLLECTIONS = {
  COMPANIES: "companies",
  KITCHENS: "kitchens",
  USERS: "users",
  KITCHEN_SECTIONS: "kitchenSections",
  KITCHEN_MEMBERSHIPS: "kitchenMemberships",
  ACCESS_CODES: "accessCodes",
  LISTS: "lists",
  CHECKLIST_ITEMS: "checklistItems",
  TEMPLATES: "templates",
  ACTIVITY_LOGS: "activityLogs",
  LIST_SNAPSHOTS: "listSnapshots",
  PHOTOS: "photos",
  COMPLETIONS: "completions",
  SUBSCRIPTION_PLANS: "subscriptionPlans",
  RECIPES: "recipes",
  RECIPE_DRAFTS: "recipeDrafts",
  SESSIONS: "sessions",
};

export const DB_COLLECTION_KEYS = [
  "companies",
  "kitchens",
  "users",
  "kitchenSections",
  "kitchenMemberships",
  "accessCodes",
  "lists",
  "checklistItems",
  "templates",
  "activityLogs",
  "listSnapshots",
  "photos",
  "completions",
  "subscriptionPlans",
  "recipes",
  "recipeDrafts",
];

export const COLLECTION_KEY_MAP = {
  companies: COLLECTIONS.COMPANIES,
  kitchens: COLLECTIONS.KITCHENS,
  users: COLLECTIONS.USERS,
  kitchenSections: COLLECTIONS.KITCHEN_SECTIONS,
  kitchenMemberships: COLLECTIONS.KITCHEN_MEMBERSHIPS,
  accessCodes: COLLECTIONS.ACCESS_CODES,
  lists: COLLECTIONS.LISTS,
  checklistItems: COLLECTIONS.CHECKLIST_ITEMS,
  templates: COLLECTIONS.TEMPLATES,
  activityLogs: COLLECTIONS.ACTIVITY_LOGS,
  listSnapshots: COLLECTIONS.LIST_SNAPSHOTS,
  photos: COLLECTIONS.PHOTOS,
  completions: COLLECTIONS.COMPLETIONS,
  subscriptionPlans: COLLECTIONS.SUBSCRIPTION_PLANS,
  recipes: COLLECTIONS.RECIPES,
  recipeDrafts: COLLECTIONS.RECIPE_DRAFTS,
};
